name: Create a release from tag

permissions: {}

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and store python artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false

      - uses: ./.github/actions/uv-setup/

      - name: Build
        run: uv build

      - name: Store python distribution artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: artifacts
          path: dist/

  release:
    permissions:
      contents: write # allow creating a release

    name: "Create and package a release"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Retrieve distribution artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
        with:
          name: artifacts
          path: dist/

      - name: Create release ${{ github.ref_name }}
        shell: bash
        run: |
          gh release create ${GITHUB_REF_NAME} --repo ${{ github.repository }} --generate-notes dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
